### ISSUE TITLE
SVG images need Access-Control-Allow-Origin headers on CDN

### ISSUE THREAD

**Issue by smith** [chef/chef-web-core#113]
When trying to use the logo images served from a CDN you get:

`XMLHttpRequest cannot load https://style.chef.io/assets/images/chef-logo.svg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4000' is therefore not allowed access.`

**Comment by cnunciato** [comment]
Fixed: http://codepen.io/cnunciato/pen/KdpVmJ?editors=100
