### ISSUE TITLE
Include modernizr

### ISSUE THREAD

**Issue by smith** [chef/chef-web-core#52]
Since it appears to be a dependency of Foundation, and it needs to be included as a separate script tag in the HEAD, include it with web core so we can use it where we need it, especially where we may not have access to a CDN, like in some on-prem environments.

**Comment by cnunciato** [comment]
It ships [with foundation-rails](https://github.com/zurb/foundation-rails/tree/master/vendor/assets/javascripts/vendor), so it should be there now. The foundation-rails README [has an example](https://github.com/zurb/foundation-rails#add-modernizr) of how to get at it via Sprockets, but we should probably add it to the Node package as well. Will look into this.

**Comment by smith** [comment]
Ok. I think I opened this because the examples or apps using it had a CDN modernizr in the HEAD, and that will not work for on-prem apps some time.

I followed the instructions in https://github.com/zurb/foundation-rails#add-modernizr in source/layouts/layout.erb and I get a 404, though.
